### ISSUE TITLE
Open Source not working

### ISSUE THREAD

**Issue by flitzcore** [scribbleX-SDA/rigel#1]
So I downloaded the opensource code and try to run index.html at folder editor and it seems stuck:
 This seems to be the problem: 
```
<label class=" form-label" for="input-model">Background Color</label>
```

![image](https://github.com/scribbleX-SDA/rigel/assets/82663653/c7df6976-a7bb-46be-8c91-46470bf7011d)

**Comment by flitzcore** [comment]
Ups, there are several CORS errors too:
```
Access to XMLHttpRequest at 'file:///home/lockrr/Documents/Code/Website%20Builder/rigel/editor/resources/google-fonts.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, isolated-app, brave, https, chrome-untrusted, data, chrome-extension, chrome.
resources/google-fonts.json:1 
        
        
       Failed to load resource: net::ERR_FAILED
builder.js:971 Uncaught DOMException: Failed to read a named property 'document' from 'Window': Blocked a frame with origin "null" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (file:///home/lockrr/Documents/Code/Website%20Builder/rigel/editor/libs/builder/builder.js:971:54)
    at HTMLIFrameElement.dispatch (file:///home/lockrr/Documents/Code/Website%20Builder/rigel/editor/js/jquery.min.js:2:43064)
    at v.handle (file:///home/lockrr/Documents/Code/Website%20Builder/rigel/editor/js/jquery.min.js:2:41048)
api.openverse.engineering/v1/auth_tokens/token/:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
```
